<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ServiceCallGraph" nsURI="http://www.dmodel.com/CallGraph" nsPrefix="scg">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="bundleManifest" value="false"/>
    <details key="modelDirectory" value="dmodel.pipeline.dt.callgraph/src-gen/java"/>
    <details key="complianceLevel" value="8.0"/>
    <details key="basePackage" value="dmodel.pipeline.dt.callgraph"/>
    <details key="modelPluginID" value=""/>
    <details key="updateClasspath" value="false"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceCallGraph">
    <eOperations name="addNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="nodes.add(seff);"/>
      </eAnnotations>
      <eParameters name="seff" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/ResourceDemandingSEFF"/>
    </eOperations>
    <eOperations name="addEdge">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="ServiceCallGraphEdge edge = ServiceCallGraphFactory.eINSTANCE.createServiceCallGraphEdge();&#xA;&#x9;&#x9;edge.setFrom(from);&#xA;&#x9;&#x9;edge.setTo(to);&#xA;&#x9;&#x9;edge.setValue(value);&#xA;&#xA;&#x9;&#x9;if (!getOutgoingEdges().containsKey(from)) {&#xA;&#x9;&#x9;&#x9;getOutgoingEdges().put(from, new BasicEList&lt;ServiceCallGraphEdge>());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;getOutgoingEdges().get(from).add(edge);&#xA;&#xA;&#x9;&#x9;if (!getIncomingEdges().containsKey(to)) {&#xA;&#x9;&#x9;&#x9;getIncomingEdges().put(to, new BasicEList&lt;ServiceCallGraphEdge>());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;getIncomingEdges().get(to).add(edge);"/>
      </eAnnotations>
      <eParameters name="from" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/ResourceDemandingSEFF"/>
      <eParameters name="to" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/ResourceDemandingSEFF"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/ResourceDemandingSEFF"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//ServiceCallGraphEdge" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEdges" upperBound="-1"
        eType="#//EdgeList" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1"
        eType="#//EdgeList" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceCallGraphEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/ResourceDemandingSEFF"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/ResourceDemandingSEFF"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeList" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//ServiceCallGraphEdge"/>
  </eClassifiers>
</ecore:EPackage>
