version: '2.2'
services:
  jmeter:
    ports:
      - '10100:8080'
    expose:
      - '8080'
    image: cipm/cocome-load
    depends_on:
      webui:
        condition: service_healthy
  dmodel:
    image: cipm/consistency
    ports:
      - '8090:8080'
    expose:
      - '8080'
      - '10133'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8080/index.html'
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      pcm-docker:
        condition: service_healthy
  pcm-docker:
    image: davmonsch/pcm-headless-rest
    ports:
    - '8100:8080'
    expose:
      - '8080'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8080'
      interval: 30s
      timeout: 10s
      retries: 5
  webui:
    image: cocome-cloud
    expose:
      - '8080'
    depends_on:
      dmodel:
        condition: service_healthy
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8080/cloud-web-frontend'
      interval: 45s
      timeout: 60s
      retries: 90
