---
project:
  rootPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample"
  sourceFolders:
  - "src/main/java"
  instrumentedPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample.instrumented"
  correspondencePath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.records/correspondence/spoon.corr"
models:
  repositoryPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models/prime_generator.repository"
  systemPath: ""
  usagePath: ""
  allocationPath: ""
  envPath: ""
entry:
  slidingWindowSize: 3000
  slidingWindowTrigger: 300
vfl:
  url: "127.0.0.1"
  port: 8080
fileBackedPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rt.start/config/external/application.yml"
