---
project:
  rootPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/"
  sourceFolders:
  - "src/main/java"
models:
  repositoryPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models_runtime/prime_generator.repository"
  systemPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models_runtime/prime_generator.system"
  usagePath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models_runtime/prime_generator.usagemodel"
  allocationPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models_runtime/prime_generator.allocation"
  envPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models_runtime/prime_generator.resourceenvironment"
  instrumentationModelPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models_runtime/prime_generator.imm"
  correspondencePath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models_runtime/prime_generator.correspondences"
  runtimeEnvironmentPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models_runtime/prime_generator.rem"
entry:
  slidingWindowSize: 1000
  slidingWindowTrigger: 360
vfl:
  url: "127.0.0.1"
  port: 8080
  simulationTime: 150000
  measurements: 10000
  validationShare: 0.1
