spring:
  profiles.active: default
---
spring:
  profiles: default

vfl:
  url: "127.0.0.1"
  port: 8080

entry:
  slidingWindowSize : 3000 # in seconds
  slidingWindowTrigger : 30 # in seconds

project:
  rootPath : "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample"
  instrumentedPath : "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample.instrumented"
  sourceFolders : ["src/main/java"]