---
project:
  listeners:
  - {}
  rootPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample"
  sourceFolders:
  - "src/main/java"
  instrumentedPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample.instrumented"
  correspondencePath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.records/correspondence/spoon.corr"
models:
  repositoryPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models/prime_generator.repository"
  systemPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models/temp_system.system"
  usagePath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models/temp_usage.usagemodel"
  allocationPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models/temp_allocation.allocation"
  envPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.rexample/models/temp_resenv.resourceenvironment"
entry:
  slidingWindowSize: 1000
  slidingWindowTrigger: 60
vfl:
  url: "127.0.0.1"
  port: 9001