---
project:
  rootPath: "/Users/david/Desktop/Dynamic Approach/Evaluation/cocome/git/cocome-cloud-jee-platform-migration/cocome-maven-project"
  sourceFolders:
  - "cloud-web-frontend/src/main/java"
  - "cloud-logic-service/cloud-logic-core-services/src/main/java"
  - "cloud-logic-service/cloud-logic-core-api/src/main/java"
  - "cloud-logic-service/cloud-logic-core-impl/src/main/java"
  - "cloud-logic-service/cloud-registry-service/src/main/java"
  - "cloud-logic-service/cloud-store-logic/store-logic-ejb/src/main/java"
  - "cloud-logic-service/cloud-store-logic/store-logic-webservice/src/main/java"
  - "cloud-logic-service/cloud-registry-client/src/main/java"
  - "cloud-logic-service/java-old-utils/src"
  - "cloud-logic-service/cloud-enterprise-logic/enterprise-logic-ejb/src/main/java"
models:
  repositoryPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git2/dModel/dmodel.root/dmodel.base.evaluation/models/cocome/models/cocome.repository"
  systemPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git2/dModel/dmodel.root/dmodel.base.evaluation/models/cocome/models/cocome.system"
  usagePath: "/Users/david/Desktop/Dynamic Approach/Implementation/git2/dModel/dmodel.root/dmodel.base.evaluation/models/cocome/models/cocome.usagemodel"
  allocationPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git2/dModel/dmodel.root/dmodel.base.evaluation/models/cocome/models/cocome.allocation"
  envPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git2/dModel/dmodel.root/dmodel.base.evaluation/models/cocome/models/cocome.resourceenvironment"
  instrumentationModelPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git2/dModel/dmodel.root/dmodel.base.evaluation/models/cocome/models/cocome.imm"
  correspondencePath: "/Users/david/Desktop/Dynamic Approach/Implementation/git2/dModel/dmodel.root/dmodel.base.evaluation/models/cocome/models/cocome.correspondences"
  runtimeEnvironmentPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git2/dModel/dmodel.root/dmodel.base.evaluation/models/cocome/models/cocome.rem"
entry:
  slidingWindowSize: 1000
  slidingWindowTrigger: 300
vfl:
  url: "127.0.0.1"
  port: 8080
  simulationTime: 150000
  measurements: 10000
  validationShare: 0.1
validationPredicates:
  condition: "AND"
  value: 0.0
  rules:
  - id: "kstest"
    operator: "less"
    value: 0.15
  - id: "avg_rel"
    operator: "less"
    value: 0.2
