---
project:
  rootPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.evaluation/models/cocome/"
  sourceFolders:
  - "src/main/java"
  instrumentedPath: ""
  correspondencePath: ""
models:
  repositoryPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.evaluation/models/cocome/models/cocome.repository"
  systemPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.evaluation/models/cocome/models/cocome.system"
  usagePath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.evaluation/models/cocome/models/cocome.usagemodel"
  allocationPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.evaluation/models/cocome/models/cocome.allocation"
  envPath: "/Users/david/Desktop/Dynamic Approach/Implementation/git/dModel/dmodel.root/dmodel.pipeline.evaluation/models/cocome/models/cocome.resourceenvironment"
entry:
  slidingWindowSize: 1800
  slidingWindowTrigger: 360
vfl:
  url: "192.168.178.64"
  port: 8080
  simulationTime: 450000
  measurements: 30000