package dmodel.designtime.system.pcm;

import org.palladiosimulator.pcm.core.composition.AssemblyContext;

import dmodel.designtime.system.pcm.data.AssemblyConflict;
import dmodel.designtime.system.pcm.impl.PCMSystemBuilder;

/**
 * 
 * Listener for conflicts that are generated by the {@link PCMSystemBuilder}
 * when there are multiple possible {@link AssemblyContext} available.
 * 
 * @author David Monschein
 *
 */
public interface IAssemblySelectionListener {

	/**
	 * Called when a conflict occurs.
	 * 
	 * @param conflict the conflict
	 */
	public void conflict(AssemblyConflict conflict);

}
