spring:
  profiles.active: default
---
spring:
  profiles: default

vfl:
  url: "127.0.0.1"
  port: 8080

entry:
  slidingWindowSize : 3600 # in seconds
  slidingWindowTrigger : 300 # in seconds